# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FBWaterfallLayout' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FBWaterfallLayout

pod 'AFNetworking', '~> 2.6.0'
pod 'SDWebImage'
pod 'CHTCollectionViewWaterfallLayout' 

  target 'FBWaterfallLayoutTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
